require("louis.plugins-setup")
require("louis.core.options")
require("louis.core.keymaps")
require("louis.plugins.nvim-tree")
require("louis.plugins.comment")
require("louis.plugins.lualine")
require("louis.core.colorscheme")
